const payloadConstants = {
  GET_PAYLOADS_REQUEST: "GET_PAYLOADS_REQUEST",
  GET_PAYLOADS_SUCCESS: "GET_PAYLOADS_SUCCESS",
  GET_PAYLOADS_FAILURE: "GET_PAYLOADS_FAILURE",
  ADD_PAYLOADS_REQUEST: "ADD_PAYLOADS_REQUEST",
  ADD_PAYLOADS_SUCCESS: "ADD_PAYLOADS_SUCCESS",
  ADD_PAYLOADS_FAILURE: "ADD_PAYLOADS_FAILURE",
  EDIT_PAYLOADS_REQUEST: "EDIT_PAYLOADS_REQUEST",
  EDIT_PAYLOADS_SUCCESS: "EDIT_PAYLOADS_SUCCESS",
  EDIT_PAYLOADS_FAILURE: "EDIT_PAYLOADS_FAILURE",
  DELETE_PAYLOADS_REQUEST: "DELETE_PAYLOADS_REQUEST",
  DELETE_PAYLOADS_SUCCESS: "DELETE_PAYLOADS_SUCCESS",
  DELETE_PAYLOADS_FAILURE: "DELETE_PAYLOADS_FAILURE",
  RESET_PAYLOAD_SUCCESS: "RESET_PAYLOAD_SEUCCESS",
};

export default payloadConstants;
