const scheduleConstants = {
  GET_SCHEDULE_TESTCASE_REQUEST: "GET_SCHEDULE_TESTCASE_REQUEST",
  GET_SCHEDULE_TESTCASE_SUCCESS: "GET_SCHEDULE_TESTCASE_SUCCESS",
  GET_SCHEDULE_TESTCASE_FAILURE: "GET_SCHEDULE_TESTCASE_FAILURE",
  ADD_SCHEDULE_REQUEST: "ADD_SCHEDULE_REQUEST",
  ADD_SCHEDULE_SUCCESS: "ADD_SCHEDULE_SUCCESS",
  ADD_SCHEDULE_FAILURE: "ADD_SCHEDULE_FAILURE",
};

export default scheduleConstants;
