const scheduleConstants = {
  GET_SCHEDULES_REQUEST: "GET_SCHEDULES_REQUEST",
  GET_SCHEDULES_SUCCESS: "GET_SCHEDULES_SUCCESS",
  GET_SCHEDULES_FAILURE: "GET_SCHEDULES_FAILURE",
  ADD_SCHEDULE_REQUEST: "ADD_SCHEDULE_REQUEST",
  ADD_SCHEDULE_SUCCESS: "ADD_SCHEDULE_SUCCESS",
  ADD_SCHEDULE_FAILURE: "ADD_SCHEDULE_FAILURE",
  RESET_SCHEDULE_SUCCESS: "RESET_SCHEDULE_SUCCESS",
};

export default scheduleConstants;
