const orgMembersConstants = {
  GET_ORG_MEMBERS_REQUEST: "GET_ORG_MEMBERS_REQUEST",
  GET_ORG_MEMBERS_SUCCESS: "GET_ORG_MEMBERS_SUCCESS",
  GET_ORG_MEMBERS_FAILURE: "GET_ORG_MEMBERS_FAILURE",
  CHANGE_MEMBER_ROLE_REQUEST: "CHANGE_MEMBER_ROLE_REQUEST",
  CHANGE_MEMBER_ROLE_SUCCESS: "CHANGE_MEMBER_ROLE_SUCCESS",
  CHANGE_MEMBER_ROLE_FAILURE: "CHANGE_MEMBER_ROLE_FAILURE",
  REMOVE_MEMBER_FROM_ORG_REQUEST: "REMOVE_MEMBER_FROM_ORG_REQUEST",
  REMOVE_MEMBER_FROM_ORG_SUCCESS: "REMOVE_MEMBER_FROM_ORG_SUCCESS",
  REMOVE_MEMBER_FROM_ORG_FAILURE: "REMOVE_MEMBER_FROM_ORG_FAILURE",
  GET_FILTERED_ORG_USERS_REQUEST: "GET_FILTERED_ORG_USERS_REQUEST",
  GET_FILTERED_ORG_USERS_SUCCESS: "GET_FILTERED_ORG_USERS_SUCCESS",
  GET_FILTERED_ORG_USERS_FAILURE: "GET_FILTERED_ORG_USERS_FAILURE",
  CLEAR_STATE: "CLEAR_STATE",
};

export default orgMembersConstants;
