const testcaseConstants = {
  GET_TESTCASES_REQUEST: "GET_TESTCASES_REQUEST",
  GET_TESTCASES_SUCCESS: "GET_TESTCASES_SUCCESS",
  GET_TESTCASES_FAILURE: "GET_TESTCASES_FAILURE",
  ADD_TESTCASES_REQUEST: "ADD_TESTCASES_REQUEST",
  ADD_TESTCASES_SUCCESS: "ADD_TESTCASES_SUCCESS",
  ADD_TESTCASES_FAILURE: "ADD_TESTCASES_FAILURE",
  EDIT_TESTCASES_REQUEST: "EDIT_TESTCASES_REQUEST",
  EDIT_TESTCASES_SUCCESS: "EDIT_TESTCASES_SUCCESS",
  EDIT_TESTCASES_FAILURE: "EDIT_TESTCASES_FAILURE",
  DELETE_TESTCASES_REQUEST: "DELETE_TESTCASES_REQUEST",
  DELETE_TESTCASES_SUCCESS: "DELETE_TESTCASES_SUCCESS",
  DELETE_TESTCASES_FAILURE: "DELETE_TESTCASES_FAILURE",
};

export default testcaseConstants;
