const projectConstants = {
    FETCH_PROJECTS: 'FETCH_PROJECTS',
    SET_PROJECTS: 'SET_PROJECTS',
    ADD_NEW_PROJECT: 'ADD_NEW_PROJECT',
    GET_PROJECT_MEMBERS_REQUEST: 'GET_PROJECT_MEMBERS_REQUEST',
    GET_PROJECT_MEMBERS_SUCCESS: 'GET_PROJECT_MEMBERS_SUCCESS',
    GET_PROJECT_MEMBERS_FAILURE: 'GET_PROJECT_MEMBERS_FAILURE',
    ADD_MEMBERS_IN_PROJECT_REQUEST: 'ADD_MEMBERS_IN_PROJECT_REQUEST',
    ADD_MEMBERS_IN_PROJECT_SUCCESS: 'ADD_MEMBERS_IN_PROJECT_SUCCESS',
    ADD_MEMBERS_IN_PROJECT_FAILURE: 'ADD_MEMBERS_IN_PROJECT_FAILURE',
    GET_ONE_PROJECT_REQUEST: 'GET_ONE_PROJECT_REQUEST',
    GET_ONE_PROJECT_SUCCESS: 'GET_ONE_PROJECT_SUCCESS',
    GET_ONE_PROJECT_FAILURE: 'GET_ONE_PROJECT_FAILURE',
    UPDATE_PROJECT_NAME_REQUEST: 'UPDATE_PROJECT_NAME_REQUEST',
    UPDATE_PROJECT_NAME_SUCCESS: 'UPDATE_PROJECT_NAME_SUCCESS',
    UPDATE_PROJECT_NAME_FAILURE: 'UPDATE_PROJECT_NAME_FAILURE',
    DELETE_PROJECT_REQUEST: 'DELETE_PROJECT_REQUEST',
    DELETE_PROJECT_SUCCESS: 'DELETE_PROJECT_SUCCESS',
    DELETE_PROJECT_FAILURE: 'DELETE_PROJECT_FAILURE',
}

export default projectConstants;