const projectConstants = {
    FETCH_PROJECTS: 'FETCH_PROJECTS',
    SET_PROJECTS: 'SET_PROJECTS',
    ADD_NEW_PROJECT: 'ADD_NEW_PROJECT',
    GET_PROJECT_MEMBERS_REQUEST: 'GET_PROJECT_MEMBERS_REQUEST',
    GET_PROJECT_MEMBERS_SUCCESS: 'GET_PROJECT_MEMBERS_SUCCESS',
    GET_PROJECT_MEMBERS_FAILURE: 'GET_PROJECT_MEMBERS_FAILURE',
}

export default projectConstants;