const teststepConstants = {
  GET_TESTSTEPS_REQUEST: "GET_TESTSTEPS_REQUEST",
  GET_TESTSTEPS_SUCCESS: "GET_TESTSTEPS_SUCCESS",
  GET_TESTSTEPS_FAILURE: "GET_TESTSTEPS_FAILURE",
  ADD_TESTSTEPS_REQUEST: "ADD_TESTSTEPS_REQUEST",
  ADD_TESTSTEPS_SUCCESS: "ADD_TESTSTEPS_SUCCESS",
  ADD_TESTSTEPS_FAILURE: "ADD_TESTSTEPS_FAILURE",
  EDIT_TESTSTEPS_REQUEST: "EDIT_TESTSTEPS_REQUEST",
  EDIT_TESTSTEPS_SUCCESS: "EDIT_TESTSTEPS_SUCCESS",
  EDIT_TESTSTEPS_FAILURE: "EDIT_TESTSTEPS_FAILURE",
  DELETE_TESTSTEPS_REQUEST: "DELETE_TESTSTEPS_REQUEST",
  DELETE_TESTSTEPS_SUCCESS: "DELETE_TESTSTEPS_SUCCESS",
  DELETE_TESTSTEPS_FAILURE: "DELETE_TESTSTEPS_FAILURE",
};

export default teststepConstants;
