const executeConstants = {
    GET_EXECUTE_REQUEST: 'GET_EXECUTE_REQUEST',
    GET_EXECUTE_SUCCESS: 'GET_EXECUTE_SUCCESS',
    GET_EXECUTE_FAILURE: 'GET_EXECUTE_FAILURE',
    ADD_EXECUTE_REQUEST: 'ADD_EXECUTE_REQUEST',
    ADD_EXECUTE_SUCCESS: 'ADD_EXECUTE_SUCCESS',
    ADD_EXECUTE_FAILURE: 'ADD_EXECUTE_FAILURE',
}

export default executeConstants;