const projectMembersConstants = {
  GET_PROJECT_MEMBERS_REQUEST: "GET_PROJECT_MEMBERS_REQUEST",
  GET_PROJECT_MEMBERS_SUCCESS: "GET_PROJECT_MEMBERS_SUCCESS",
  GET_PROJECT_MEMBERS_FAILURE: "GET_PROJECT_MEMBERS_FAILURE",
  ADD_MEMBERS_IN_PROJECT_REQUEST: "ADD_MEMBERS_IN_PROJECT_REQUEST",
  ADD_MEMBERS_IN_PROJECT_SUCCESS: "ADD_MEMBERS_IN_PROJECT_SUCCESS",
  ADD_MEMBERS_IN_PROJECT_FAILURE: "ADD_MEMBERS_IN_PROJECT_FAILURE",
  REMOVE_MEMBERS_IN_PROJECT_REQUEST: "REMOVE_MEMBERS_IN_PROJECT_REQUEST",
  REMOVE_MEMBERS_IN_PROJECT_SUCCESS: "REMOVE_MEMBERS_IN_PROJECT_SUCCESS",
  REMOVE_MEMBERS_IN_PROJECT_FAILURE: "REMOVE_MEMBERS_IN_PROJECT_FAILURE",
};

export default projectMembersConstants;
