const endpointConstants = {
    ADD_ENDPOINT_REQUEST: 'ADD_ENDPOINT_REQUEST',
    ADD_ENDPOINT_SUCCESS: 'ADD_ENDPOINT_SUCCESS',
    ADD_ENDPOINT_FAILURE: 'ADD_ENDPOINT_FAILURE',
    GET_ENDPOINT_REQUEST: 'GET_ENDPOINT_REQUEST',
    GET_ENDPOINT_SUCCESS: 'GET_ENDPOINT_SUCCESS',
    GET_ENDPOINT_FAILURE: 'GET_ENDPOINT_FAILURE',
    EDIT_ENDPOINT_REQUEST: 'EDIT_ENDPOINT_REQUEST',
    EDIT_ENDPOINT_SUCCESS: 'EDIT_ENDPOINT_SUCCESS',
    EDIT_ENDPOINT_FAILURE: 'EDIT_ENDPOINT_FAILURE',
    DELETE_ENDPOINT_REQUEST: 'DELETE_ENDPOINT_REQUEST',
    DELETE_ENDPOINT_SUCCESS: 'DELETE_ENDPOINT_SUCCESS',
    DELETE_ENDPOINT_FAILURE: 'DELETE_ENDPOINT_FAILURE',
};

export default endpointConstants;