const orgConstants = {
  GET_ORGANIZATIONS_REQUEST: "GET_ORGANIZATIONS_REQUEST",
  GET_ORGANIZATIONS_SUCCESS: "GET_ORGANIZATIONS_SUCCESS",
  GET_ORGANIZATIONS_FAILURE: "GET_ORGANIZATIONS_FAILURE",
  ADD_ORGANIZATION_REQUEST: "ADD_ORGANIZATION_REQUEST",
  ADD_ORGANIZATION_SUCCESS: "ADD_ORGANIZATION_SUCCESS",
  ADD_ORGANIZATION_FAILURE: "ADD_ORGANIZATION_FAILURE",
  EDIT_ORGANIZATION_REQUEST: "EDIT_ORGANIZATION_REQUEST",
  EDIT_ORGANIZATION_SUCCESS: "EDIT_ORGANIZATION_SUCCESS",
  EDIT_ORGANIZATION_FAILURE: "EDIT_ORGANIZATION_FAILURE",
  INVITE_USERS_IN_ORGANIZATION_REQUEST: "INVITE_USERS_IN_ORGANIZATION_REQUEST",
  INVITE_USERS_IN_ORGANIZATION_SUCCESS: "INVITE_USERS_IN_ORGANIZATION_SUCCESS",
  INVITE_USERS_IN_ORGANIZATION_FAILURE: "INVITE_USERS_IN_ORGANIZATION_FAILURE",
  LEAVE_ORGANIZATION_REQUEST: "LEAVE_ORGANIZATION_REQUEST",
  LEAVE_ORGANIZATION_SUCCESS: "LEAVE_ORGANIZATION_SUCCESS",
  LEAVE_ORGANIZATION_FAILURE: "LEAVE_ORGANIZATION_FAILURE",
  DELETE_ORGANIZATION_REQUEST: "DELETE_ORGANIZATION_REQUEST",
  DELETE_ORGANIZATION_SUCCESS: "DELETE_ORGANIZATION_SUCCESS",
  DELETE_ORGANIZATION_FAILURE: "DELETE_ORGANIZATION_FAILURE",
  CLEAR_STATE: "CLEAR_STATE",
};

export default orgConstants;
