const headerConstants = {
  GET_HEADERS_REQUEST: "GET_HEADERS_REQUEST",
  GET_HEADERS_SUCCESS: "GET_HEADERS_SUCCESS",
  GET_HEADERS_FAILURE: "GET_HEADERS_FAILURE",
  ADD_HEADERS_REQUEST: "ADD_HEADERS_REQUEST",
  ADD_HEADERS_SUCCESS: "ADD_HEADERS_SUCCESS",
  ADD_HEADERS_FAILURE: "ADD_HEADERS_FAILURE",
  EDIT_HEADERS_REQUEST: "EDIT_HEADERS_REQUEST",
  EDIT_HEADERS_SUCCESS: "EDIT_HEADERS_SUCCESS",
  EDIT_HEADERS_FAILURE: "EDIT_HEADERS_FAILURE",
  DELETE_HEADERS_REQUEST: "DELETE_HEADERS_REQUEST",
  DELETE_HEADERS_SUCCESS: "DELETE_HEADERS_SUCCESS",
  DELETE_HEADERS_FAILURE: "DELETE_HEADERS_FAILURE",
};

export default headerConstants;
