const testsuiteConstants = {
    GET_TESTSUITES_REQUEST: "GET_TESTSUITES_REQUEST",
    GET_TESTSUITES_SUCCESS: "GET_TESTSUITES_SUCCESS",
    GET_TESTSUITES_FAILURE: "GET_TESTSUITES_FAILURE",
    ADD_TESTSUITE_REQUEST: "ADD_TESTSUITE_REQUEST",
    ADD_TESTSUITE_SUCCESS: "ADD_TESTSUITE_SUCCESS",
    ADD_TESTSUITE_FAILURE: "ADD_TESTSUITE_FAILURE",
    EDIT_TESTSUITE_REQUEST: "EDIT_TESTSUITE_REQUEST",
    EDIT_TESTSUITE_SUCCESS: "EDIT_TESTSUITE_SUCCESS",
    EDIT_TESTSUITE_FAILURE: "EDIT_TESTSUITE_FAILURE",
    DELETE_TESTSUITE_REQUEST: "DELETE_TESTSUITE_REQUEST",
    DELETE_TESTSUITE_SUCCESS: "DELETE_TESTSUITE_SUCCESS",
    DELETE_TESTSUITE_FAILURE: "DELETE_TESTSUITE_FAILURE",
};

export default testsuiteConstants;
