const facetAdminConstants = {
  GET_ORGANIZATIONS_ADMIN_REQUEST: "GET_ORGANIZATIONS_ADMIN_REQUEST",
  GET_ORGANIZATIONS_ADMIN_SUCCESS: "GET_ORGANIZATIONS_ADMIN_SUCCESS",
  GET_ORGANIZATIONS_ADMIN_FAILURE: "GET_ORGANIZATIONS_ADMIN_FAILURE",
  GET_ORGANIZATION_ADMIN_REQUEST: "GET_ORGANIZATION_ADMIN_REQUEST",
  GET_ORGANIZATION_ADMIN_SUCCESS: "GET_ORGANIZATION_ADMIN_SUCCESS",
  GET_ORGANIZATION_ADMIN_FAILURE: "GET_ORGANIZATION_ADMIN_FAILURE",
  GET_USERS_ADMIN_REQUEST: "GET_USERS_ADMIN_REQUEST",
  GET_USERS_ADMIN_SUCCESS: "GET_USERS_ADMIN_SUCCESS",
  GET_USERS_ADMIN_FAILURE: "GET_USERS_ADMIN_FAILURE",
};

export default facetAdminConstants;
