const scheduleConstants = {
    GET_SCHEDULE_TESTSUITE_REQUEST: 'GET_SCHEDULE_TESTSUITE_REQUEST',
    GET_SCHEDULE_TESTSUITE_SUCCESS: 'GET_SCHEDULE_TESTSUITE_SUCCESS',
    GET_SCHEDULE_TESTSUITE_FAILURE: 'GET_SCHEDULE_TESTSUITE_FAILURE',
    ADD_SCHEDULE_REQUEST: 'ADD_SCHEDULE_REQUEST',
    ADD_SCHEDULE_SUCCESS: 'ADD_SCHEDULE_SUCCESS',
    ADD_SCHEDULE_FAILURE: 'ADD_SCHEDULE_FAILURE',
}

export default scheduleConstants;