const environmentConstants = {
    GET_ENVIRONMENTS_REQUEST: 'GET_ENVIRONMENTS_REQUEST',
    GET_ENVIRONMENTS_SUCCESS: 'GET_ENVIRONMENTS_SUCCESS',
    GET_ENVIRONMENTS_FAILURE: 'GET_ENVIRONMENTS_FAILURE',
    ADD_ENVIRONMENTS_REQUEST: 'ADD_ENVIRONMENTS_REQUEST',
    ADD_ENVIRONMENTS_SUCCESS: 'ADD_ENVIRONMENTS_SUCCESS',
    ADD_ENVIRONMENTS_FAILURE: 'ADD_ENVIRONMENTS_FAILURE',
}

export default environmentConstants;