const testsuiteConstants = {
    GET_TESTSUITES_REQUEST: 'GET_TESTSUITES_REQUEST',
    GET_TESTSUITES_SUCCESS: 'GET_TESTSUITES_SUCCESS',
    GET_TESTSUITES_FAILURE: 'GET_TESTSUITES_FAILURE',
    ADD_TESTSUITES_REQUEST: 'ADD_TESTSUITES_REQUEST',
    ADD_TESTSUITES_SUCCESS: 'ADD_TESTSUITES_SUCCESS',
    ADD_TESTSUITES_FAILURE: 'ADD_TESTSUITES_FAILURE',
}

export default testsuiteConstants;