const superAdminConstants = {
    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILURE: 'GET_ALL_USERS_FAILURE',
    ADD_ADMINS_REQUEST: 'ADD_ADMINS_REQUEST',
    ADD_ADMINS_SUCCESS: 'ADD_ADMINS_SUCCESS',
    ADD_ADMINS_FAILURE: 'ADD_ADMINS_FAILURE',
}

export default superAdminConstants;