const projectConstants = {
  GET_PROJECTS_REQUEST: "GET_PROJECTS_REQUEST",
  GET_PROJECTS_SUCCESS: "GET_PROJECTS_SUCCESS",
  GET_PROJECTS_FAILURE: "GET_PROJECTS_FAILURE",
  ADD_PROJECT_REQUEST: "ADD_PROJECT_REQUEST",
  ADD_PROJECT_SUCCESS: "ADD_PROJECT_SUCCESS",
  ADD_PROJECT_FAILURE: "ADD_PROJECT_FAILURE",
  GET_PROJECT_REQUEST: "GET_PROJECT_REQUEST",
  GET_PROJECT_SUCCESS: "GET_PROJECT_SUCCESS",
  GET_PROJECT_FAILURE: "GET_PROJECT_FAILURE",
  UPDATE_PROJECT_NAME_REQUEST: "UPDATE_PROJECT_NAME_REQUEST",
  UPDATE_PROJECT_NAME_SUCCESS: "UPDATE_PROJECT_NAME_SUCCESS",
  UPDATE_PROJECT_NAME_FAILURE: "UPDATE_PROJECT_NAME_FAILURE",
  DELETE_PROJECT_REQUEST: "DELETE_PROJECT_REQUEST",
  DELETE_PROJECT_SUCCESS: "DELETE_PROJECT_SUCCESS",
  DELETE_PROJECT_FAILURE: "DELETE_PROJECT_FAILURE",
};

export default projectConstants;
