const environmentConstants = {
  GET_ENVIRONMENTS_REQUEST: "GET_ENVIRONMENTS_REQUEST",
  GET_ENVIRONMENTS_SUCCESS: "GET_ENVIRONMENTS_SUCCESS",
  GET_ENVIRONMENTS_FAILURE: "GET_ENVIRONMENTS_FAILURE",
  ADD_ENVIRONMENTS_REQUEST: "ADD_ENVIRONMENTS_REQUEST",
  ADD_ENVIRONMENTS_SUCCESS: "ADD_ENVIRONMENTS_SUCCESS",
  ADD_ENVIRONMENTS_FAILURE: "ADD_ENVIRONMENTS_FAILURE",
  EDIT_ENVIRONMENTS_REQUEST: "EDIT_ENVIRONMENTS_REQUEST",
  EDIT_ENVIRONMENTS_SUCCESS: "EDIT_ENVIRONMENTS_SUCCESS",
  EDIT_ENVIRONMENTS_FAILURE: "EDIT_ENVIRONMENTS_FAILURE",
  DELETE_ENVIRONMENTS_REQUEST: "DELETE_ENVIRONMENTS_REQUEST",
  DELETE_ENVIRONMENTS_SUCCESS: "DELETE_ENVIRONMENTS_SUCCESS",
  DELETE_ENVIRONMENTS_FAILURE: "DELETE_ENVIRONMENTS_FAILURE",
};

export default environmentConstants;
