const modalConstants = {
    SELECT_FIELD: 'SELECT_FIELD',
    ADD_KEY_FIELD: 'ADD_KEY_FIELD',
    ADD_VALUE_FIELD: 'ADD_VALUE_FIELD',
    ADD_VALIDATIONS_FIELD: 'ADD_VALIDATIONS_FIELD',
    SAVE_FIELD: 'SAVE_FIELD'
}

export default modalConstants;