const testcaseConstants = {
    GET_TESTCASES_REQUEST: 'GET_TESTCASES_REQUEST',
    GET_TESTCASES_SUCCESS: 'GET_TESTCASES_SUCCESS',
    GET_TESTCASES_FAILURE: 'GET_TESTCASES_FAILURE',
    ADD_TESTCASES_REQUEST: 'ADD_TESTCASES_REQUEST',
    ADD_TESTCASES_SUCCESS: 'ADD_TESTCASES_SUCCESS',
    ADD_TESTCASES_FAILURE: 'ADD_TESTCASES_FAILURE',
}

export default testcaseConstants;