const reportsConstants = {
  GET_REPORTS_REQUEST: "GET_REPORTS_REQUEST",
  GET_REPORTS_SUCCESS: "GET_REPORTS_SUCCESS",
  GET_REPORTS_FAILURE: "GET_REPORTS_FAILURE",
  GET_REPORT_REQUEST: "GET_REPORT_REQUEST",
  GET_REPORT_SUCCESS: "GET_REPORT_SUCCESS",
  GET_REPORT_FAILURE: "GET_REPORT_FAILURE",
  ADD_REPORTS_REQUEST: "ADD_REPORTS_REQUEST",
  ADD_REPORTS_SUCCESS: "ADD_REPORTS_SUCCESS",
  ADD_REPORTS_FAILURE: "ADD_REPORTS_FAILURE",
  EDIT_REPORTS_REQUEST: "EDIT_REPORTS_REQUEST",
  EDIT_REPORTS_SUCCESS: "EDIT_REPORTS_SUCCESS",
  EDIT_REPORTS_FAILURE: "EDIT_REPORTS_FAILURE",
  DELETE_REPORTS_REQUEST: "DELETE_REPORTS_REQUEST",
  DELETE_REPORTS_SUCCESS: "DELETE_REPORTS_SUCCESS",
  DELETE_REPORTS_FAILURE: "DELETE_REPORTS_FAILURE",
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",
  PAGE_SIZE: 20,
};

export default reportsConstants;
