const payloadConstants = {
    GET_PAYLOADS_REQUEST: 'GET_PAYLOADS_REQUEST',
    GET_PAYLOADS_SUCCESS: 'GET_PAYLOADS_SUCCESS',
    GET_PAYLOADS_FAILURE: 'GET_PAYLOADS_FAILURE',
    ADD_PAYLOADS_REQUEST: 'ADD_PAYLOADS_REQUEST',
    ADD_PAYLOADS_SUCCESS: 'ADD_PAYLOADS_SUCCESS',
    ADD_PAYLOADS_FAILURE: 'ADD_PAYLOADS_FAILURE',
}

export default payloadConstants;